# Generated by Django 2.2.6 on 2019-11-03 09:01

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric and -, _', regex='^[a-zA-Z0-9,-,_]*$'), django.core.validators.MinLengthValidator(limit_value=6, message='username must be 6 to 20 characters long'), django.core.validators.MaxLengthValidator(limit_value=20, message='username must be 6 to 20 characters long')])),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
